foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/runonce.sh

If runonce.sh is run multiple times, meshtasticd.service will no longer be borked

---

foxbuntu/project/cfg/BoardConfig_IPC/overlay/overlay-luckfox-ubuntu/etc/rc.local

remove filesystem resize from rc.local (is already present in runonce)

---

environment-setup/foxbunto_env_setup.sh

fix small error in chroot section of build_env

---

environment-setup/foxbunto_env_setup.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/etc/issue
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/etc/pam.d/common-password

qrencode also added to dev env

Default password for femto is now femto. Must be changed on first login.

---

environment-setup/femtofox.chroot
environment-setup/foxbuntu-builder.sh

Put in some checks, chroot script injection, fixed menu and dependencies, moved initial chroot commands to chroot script, fixed cli args, updated usage and added new args including --chroot-script

Foxbuntu Image Builder

---

environment-setup/foxbuntu-builder.sh

Fixed typo in usage.  arg should have read sdk_install not install

 foxbuntu-builder.sh

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/usbconfig.sh

Added reminder to remove USB drive after USB config is complete

---

environment-setup/foxbuntu-builder.sh

clone_repos now tries 3 times on each repo and exits if it fails.  Thanks to spudgunman on discord now script checks for Ubuntu 22.04 and checks if repos already exists on SDk Install.

Added some more safety features (seatbelts and airbags)

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/etc/dhcp/dhclient-exit-hooks.d/restart-meshtasticd

I was totally wrong about meshtasticd not listening when network is changed and this is not needed.

Removed dhclient hook.

---

environment-setup/foxbuntu-builder.sh

This will allow us to install the sdk via the following command:   wget https://raw.githubusercontent.com/noon92/femtofox/refs/heads/main/environment-setup/foxbuntu-builder.sh -O foxbuntu-builder.sh

Use already fetched chroot script.

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/wifi-mesh-control.sh

New code syncs wlan0 statte with meshtastic clients (settings, network, wifi enabled).

Replaced wifi-mesh-control code.

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/etc/update-motd.d/00-header
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/etc/wpa_supplicant/wpa_supplicant.conf
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-network-config.sh

Also some cosmetic changes and improvements in femto-config and femto-network-config

Fix issue with PSKs not interpreting special characters correctly

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-runonce.sh

Corrected first boot logging

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-kernel-modules.sh

Also works as a standalone script (femto-kernel-modules.sh) with argument -x

Add kernel modules menu to femto-config utilities

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/etc/chrony/chrony.conf

Increase chrony minimum poll time to 4.5 hours

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-meshtasticd-config.sh

I got sick of manually testing mesh connectivity from CLI

Added mesh connectivity test feature

---

environment-setup/femtofox.chroot
environment-setup/foxbuntu-builder.sh

Fix for Image Update not including env changes.
Added python-is-python3 python3.10-venv to aid in python development. Added software-properties-common so we can take advantage of the new Meshtastic PPA.

Image Builder Fix and Chroot Changes

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/wifi-mesh-control.sh

Reverted to original but added Josh's error handler to check if meshtastic was running.

Last PR had errors.

---

environment-setup/foxbuntu-builder.sh

Added rebuild chroot and did some cleanup.
Rebuild Chroot wipes and rebuilds rootfs and chroot.

Added Rebuild Chroot menu option.

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/home/pico/.bashrc
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-runonce.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-software.sh

try bashrc update and remove meshtastic wifi updaste from runonce

---

environment-setup/foxbuntu-builder.sh

Fixed typo.

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/wifi-mesh-control.sh

Removing bad code.

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/wifi-mesh-control.sh

Wifi mesh control does nothing now if meshtasticd is not using SPI

Wifi mesh control checks SPI

---

environment-setup/femtofox.chroot

added lsof and also spi-tools (not needed but useful for development)

  wifi mesh control needs

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-wifi-config.sh

Restarting wpa_supplicant, calling dhclient and setting wifi enable on meshtastic was not needed.

Fixed wifi setup menu.

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/etc/sysctl.conf

Reduce swappiness to reduce SD wear (thanks @joshbowyer)

---

environment-setup/femtofox.chroot

Added luma packaged for oled.

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/meshing_around.sh

New working

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-network-config.sh

Add "disable logging" feature

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-software.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/contact_client.sh

I didn't like the name curses-client so I came up with "Contact".  Because ya know "console" and it's for making contact with people.  I think I got all the references in the shell scripts in this PR...

Renamed curses client to 'Contact'

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/etc/systemd/system/meshtasticd.service.d/override.conf

Revert "Override for meshtasticd boot order."

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-runonce.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-usb-config-tool.sh

Add colors to first boot and usbconfig script's outputs to improve console readability

---

assets/femtofox-config.txt
environment-setup/foxbuntu-builder.sh
foxbuntu_install.md

replace https://github.com/noon92/ with https://github.com/femtofox/

Update repo address

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/etc/femto.conf
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-runonce.sh

Bug fixes for new firstboot flag.

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-kernel-modules.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-runonce.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-software.sh

Previously selected option is preselected.

Menus now remember previous selections

---

environment-setup/femtofox.chroot
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/etc/apt/apt.conf.d/20auto-upgrades

Disabled service and changed apt setting.

Disabled unattended-upgrades and apt periodic updates

---

environment-setup/femtofox.chroot
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config

Transition to official release of meshtasticd

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/etc/systemd/system/ttyd.service
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-network-config.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-runonce.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-utils.sh

Generate ttyd SSL encryption on first boot and whenever hostname changes

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-license.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-meshtasticd-config.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-network-config.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-runonce.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-software.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-utils.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/contact_client.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/meshing_around.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/mosquitto_mqtt_broker.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/mosquitto_mqtt_client.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/samba.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/tc2_bbs.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/ttyd.sh

May (probably) require further commits

Revamp software menu system and improve package manager

---

environment-setup/femtofox.chroot
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/etc/systemd/system/time-monitor.service
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/time_change.sh

Currently set to detect a 1 week change in time.
Logs to /var/log/time_change.log

time-monitor service to restart meshtasticd

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-utils.sh

Fix small niggling error in sysinfo cpu

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-meshtasticd-config.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-utils.sh

Check if meshtasticd service is running before trying to interact with it, and offer to launch the service if not

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-watchclock-dog.sh

While loop checks if meshtasticd is running and if not nopes out until next loop.

Watchclock Dog checks if meshtasticd is running

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-software.sh

Improve installation usability by allowing pip installs to display live on screen

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/root/.dialogrc
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-install-wizard.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-meshtasticd-config.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-meshtasticd-lora-dialogs.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-software.sh

Now user can configure all lora settings from a menu, or a wizard.
Integrated into the main wizard as well.
About 750 lines of code.

Massive overhaul of LoRa settings menus

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-runonce.sh

Revert runonce swapfile

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-pinout.sh

Fix small pinouts issues

---

environment-setup/femtofox.chroot
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-install-wizard.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/control_for_meshtastic.sh

Revamp settings menu to take advantage of Control by @pdxlocations

---

environment-setup/femtofox.chroot
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-install-wizard.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-utils.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/control_for_meshtastic.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/meshing_around.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/tc2_bbs.sh

This stops running services and restarts them after Control exits.

Prevent conflicts between Control for Meshtastic and running BBS applications

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-software.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/contact_client.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/control_for_meshtastic.sh
foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/packages/femto_argument_parse.sh

Fix "run software" command in software menu, re-enable for Contact and Control

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-software.sh

Fix software install/upgrade exit status false reports

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-meshtasticd-config.sh

Thanks! @Will-wastelander
Closes #388

Fix meshtastic install/upgrade in menus

---

foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config

Combined meshtastic wifi sync and avahi daemon service managers into a single function
